feat: add top clicked in predictive layer
empathyco/x-archetype pull request #118
Opened 2022-06-22 10:49 UTC by mnavarroespinosa

EX-6350

2022-06-22 12:09 UTC, tiborux commented
Remove the recommendations from the desktop.vue:

```
    <LocationProvider v-if="!$x.query.search" location="no_query">
      <Recommendations />
    </LocationProvider>
```

With the change that you did, you add a horizontal scroll in the main template.

I know that this is not related to this pr, but i think that we can remove it, what do you think?

2022-06-22 12:59 UTC, ajperezbau requested changes

2022-06-22 13:05 UTC, tiborux commented on src/components/results/recommendations.vue
> +    v-if="!$x.query.searchBox && $x.recommendations.length > 0"
Adding this check here, we are not showing the top clicked on no results situations.

2022-06-22 15:17 UTC, mnavarroespinosa commented on src/components/results/recommendations.vue
> +    <SlidingPanel
You're right, I've restored the recommendations component that is used for the no results.

2022-06-22 15:18 UTC, mnavarroespinosa commented on src/components/results/recommendations.vue
> +    v-if="!$x.query.searchBox && $x.recommendations.length > 0"
I've restored this component.

2022-06-22 15:18 UTC, mnavarroespinosa commented on src/components/results/recommendations.vue
> +    <SlidingPanel
Sure, thanks!

2022-06-22 15:18 UTC, mnavarroespinosa commented on src/components/predictive-layer.vue
> +      <div class="x-list x-list--vertical x-list--gap-06 x-list__item--expand x-flex-1">
Thanks, I think that works great!

2022-06-22 16:55 UTC, mnavarroespinosa commented
> Remove the recommendations from the desktop.vue:
> 
> ```
>     <LocationProvider v-if="!$x.query.search" location="no_query">
>       <Recommendations />
>     </LocationProvider>
> ```
> 
> With the change that you did, you add a horizontal scroll in the main template.
> 
> I know that this is not related to this pr, but i think that we can remove it, what do you think?

You're right! I've removed it from `main.vue`.

2022-06-23 07:06 UTC, tiborux commented on src/components/predictive-layer/custom-recommendations.vue
> +<template>
Can we name the component: `sliding-recommendations`?

2022-06-23 08:23 UTC, ajperezbau commented
> > Remove the recommendations from the desktop.vue:
> > ```
> >     <LocationProvider v-if="!$x.query.search" location="no_query">
> >       <Recommendations />
> >     </LocationProvider>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With the change that you did, you add a horizontal scroll in the main template.
> > I know that this is not related to this pr, but i think that we can remove it, what do you think?
> 
> @tiborux You're right! I've removed it from `main.vue`.

Now that the recommendations component is as before it can be added to the main component again without adding the horizontal scroll.

2022-06-23 08:45 UTC, ajperezbau commented
The last commit is to fix the sliding panel throwing an error where it doesn't contain an element.

I think the `if` checking the totalResults is not needed, but if it is, it can be placed in the wrapper `div`.

![Screenshot 2022-06-23 at 09 39 18](https://user-images.githubusercontent.com/75546736/175256574-2a3a5178-5690-400d-8116-41d799631c7e.png)

2022-06-23 08:45 UTC, ajperezbau approved these changes

2022-06-23 09:52 UTC, tiborux approved these changes

2022-06-23 09:53 UTC, merged