feat: style and config sorting filters panel
empathyco/x-archetype pull request #120
Opened 2022-06-23 11:22 UTC by diegopf

EX-6345

2022-06-23 13:04 UTC, tiborux commented
Yous miss the divider between facets:

![image](https://user-images.githubusercontent.com/6597815/175305252-a15722a7-d7d0-499a-a2b6-85c95e083073.png)

2022-06-23 13:20 UTC, tiborux commented on src/components/search/sort.vue
> +  <CustomHeaderTogglePanel :data-test="'sort'">
You have to add here a gap of 16px:

![image](https://user-images.githubusercontent.com/6597815/175308633-f4793e00-cf44-48c3-bbbc-da3946e2d687.png)

2022-06-23 13:49 UTC, tiborux commented on src/components/mobile/mobile-close-aside.vue
> +      {{ $t('selectedFilters.clear', { selectedFiltersNumber: selectedFilters.length }) }}
Remove the white spaces in the translations:

`"clear": "Clear {selectedFiltersNumber} filters"`

2022-06-23 14:07 UTC, tiborux requested changes
gj man

2022-06-24 08:27 UTC, tiborux commented on src/i18n/messages/es.messages.json
> +      "showAside": "Ordenar & filtrar"
```suggestion
      "showAside": "Ordenar y filtrar"
```

2022-06-24 08:28 UTC, tiborux commented on src/i18n/messages/es.messages.json
>        "hideAside": "Ocultar Filtros",
remove this message is not longer neccesary.

2022-06-24 10:43 UTC, ajperezbau commented
![image](https://user-images.githubusercontent.com/75546736/175519223-e82dac74-f971-4c14-b9e1-690777477862.png)

The line in the mobile panel should be full width.

2022-06-24 11:03 UTC, ajperezbau requested changes

2022-06-24 11:03 UTC, ajperezbau commented on src/components/desktop/desktop-aside.vue
> +        class="x-list--gap-06 x-list--padding-05 x-list--padding-top"
These classes can be deleted if the facets headers spacings are set using the padding token.

2022-06-24 11:03 UTC, ajperezbau commented on src/components/mobile/mobile-aside.vue
> +      <Sort class="x-list--padding-04 x-list--padding-bottom" />
These classes can be deleted if the facets headers spacings are set using the padding token.
Also the CustomFacets ones.

2022-06-24 11:03 UTC, ajperezbau commented on src/components/mobile/mobile-close-aside.vue
> +      x-padding--05 x-padding--top-03 x-padding--bottom-04
```suggestion
      x-padding--00 x-padding--top-03 x-padding--bottom-04
```

2022-06-27 08:23 UTC, mnavarroespinosa commented
The selected sorting option in the facet title font size should be 14px instead of 16px.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/77450928/175894118-6240c8b2-304f-44d6-8d91-16f9db8bf62a.png">

2022-06-27 08:28 UTC, mnavarroespinosa commented
The space between the modal title and the facets list is too large:

![image](https://user-images.githubusercontent.com/77450928/175894670-e70949bf-c4b9-450c-8f71-8a3aa4c07203.png)


Design:

![image](https://user-images.githubusercontent.com/77450928/175895024-367bc77a-6192-4ba9-beaf-f936baf03293.png)

2022-06-27 09:13 UTC, tiborux approved these changes

2022-06-27 09:36 UTC, merged