feat(i18n): update translations
empathyco/x-archetype pull request #130
Opened 2022-06-24 09:20 UTC by tiborux

EX-6461

2022-06-24 11:45 UTC, CachedaCodes requested changes

2022-06-24 11:45 UTC, CachedaCodes commented on src/i18n/messages.types.ts
> -    hideAside: string;
This one is still being used in the mobile layout.

2022-06-24 11:45 UTC, CachedaCodes commented on src/i18n/messages/en.messages.json
> +      "message": "Sorry but there are no results for <span class=\"x-text x-text--accent x-text--bold\">'{query}'</span>. You may be interested in these products"
This is not the message in the designs for the `no-results` (no dot after the first phrase and a line break instead). Should be changed here or there's a task for it? (A little styling is required).

![image](https://user-images.githubusercontent.com/7124620/175527327-edd8282d-5e95-4e4a-af5e-737595b1cb7d.png)

2022-06-24 11:45 UTC, CachedaCodes commented on src/i18n/messages/en.messages.json
> +      "message": "VIEW ALL"
This is not the message for the partials in the designs. If we should change it in this task it should be:

```suggestion
      "message": "View all results ({totalResults})"
```

![image](https://user-images.githubusercontent.com/7124620/175527533-debb1ab5-51ff-4a74-9446-81029b691c0b.png)

2022-06-27 07:32 UTC, mnavarroespinosa commented on src/i18n/messages/en.messages.json
> +      "all": "Show more"
Shouldn't this still be 'All'?

```suggestion
      "all": "All"
```

2022-06-28 06:50 UTC, CachedaCodes approved these changes

2022-06-28 07:12 UTC, mnavarroespinosa approved these changes

2022-06-28 07:13 UTC, merged