EX-6744 Change history queries confirmation dialog text
empathyco/x-archetype pull request #155
Opened 2022-08-01 07:21 UTC by annacv

[EX-6744](https://searchbroker.atlassian.net/browse/EX-6744)

2022-08-01 08:03 UTC, herrardo requested changes
I wrote the text in this way to not use "you" or "your", but then i realized that we already use that way of communicating with the customer on the My History panel, so in that case, i like better your suggestion:

https://searchbroker.atlassian.net/browse/EX-6743?focusedCommentId=156315

2022-08-01 10:20 UTC, CachedaCodes commented
I agree with @herrardo, I find `If you disable the History Queries feature, your search history will be deleted.` better.

2022-08-01 10:21 UTC, CachedaCodes requested changes
I agree with @herrardo, I find `If you disable the History Queries feature, your search history will be deleted.` better.

2022-08-02 07:29 UTC, herrardo approved these changes

2022-08-02 07:56 UTC, CachedaCodes approved these changes

2022-08-02 07:57 UTC, merged