Feature/ update archetype feature locations
empathyco/x-archetype pull request #179
Opened 2022-09-29 15:38 UTC by annacv

[EX-7078](https://searchbroker.atlassian.net/browse/EX-7078)
# Pull request template
 

- Update x-components to `3.0.0-alpha.183 version`
- Implement `queryFeature` prop in `CustomQueryPreview` component

## Motivation and context

Update archetype with feature/locations in NQs and Queries preview

- [x] Dependencies. If any, specify: x-components to `3.0.0-alpha.183 version`
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?

- Check in VueDevTools that `QueryPreview` component has the `QueryFeature` prop defined
- When X is opened, the request of the `no-search` carrousels is sent with the origin `customer:no-search`.
- Clicking in `no-search` carrousels's `view-more` button fires a new search request with the origin `customer:no-search`.
- Clicking in `next-queries` in results grid fires new search request with the origin `next_query:results`

Tests performed according to [testing guidelines](https://github.com/empathyco/x/blob/main/.github/contributing/tests.md): 

## Checklist:

- [x] My code follows the **[style guidelines](https://github.com/empathyco/x/blob/main/.github/CONTRIBUTING.md#style-guides)** of this project.
- [x] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-09-30 11:02 UTC, LuisMartinez15 approved these changes
good job!

2022-10-03 08:33 UTC, javieri-empathy requested changes

2022-10-03 08:33 UTC, javieri-empathy commented on src/components/pre-search/custom-query-preview.vue
>    export default class CustomQueryPreview extends Vue {
Right now this is sending the `origin=customer:results` parameter to the search.

![image](https://user-images.githubusercontent.com/68222542/193534170-190e8cce-c17a-4b24-bdbe-8cc64cb3b601.png)


 The location should be `no_query`. To do so, in `main.vue` you can wrap the `CustomQueryPreview` component with a `LocationProvider` component.

2022-10-03 09:20 UTC, javieri-empathy commented on src/components/main.vue
> +    <LocationProvider location="no-query">
It's `no_query` 😅
```suggestion
    <LocationProvider location="no_query">
```

2022-10-03 09:27 UTC, LuisMartinez15 requested changes
check javi's comment

2022-10-03 09:29 UTC, javieri-empathy approved these changes

2022-10-03 09:42 UTC, LuisMartinez15 approved these changes

2022-10-03 09:59 UTC, merged