fix(webpack): output webpack related files to `webpack-generated` virtual folder
empathyco/x-archetype pull request #181
Opened 2022-09-30 09:55 UTC by diegopf

This PR aims to solve the issue we currently have to debug `*.vue` files. In the devtools is though to find what you want to debug through `cmd + p` since it lists several entries for the same file. This is due to webpack handling of this type of files. The vue-cli and vue repositories contain several issues related to the same problem (see for example: https://github.com/vuejs/vue-cli/issues/2897, https://github.com/vuejs/vue-cli/issues/2978 or https://github.com/vuejs/vue/issues/11023)

I have found the easiest solution for us is described on this [blog post](https://www.mistergoodcat.com/post/the-joy-that-is-source-maps-with-vuejs-and-typescript).

You can test this by comparing the content on the devtools:

Before
![image](https://user-images.githubusercontent.com/7504736/193244483-def6b52a-690c-42f8-a7e0-be030ae5b1ac.png)

After
![image](https://user-images.githubusercontent.com/7504736/193244596-cf2c88fe-fdc9-4865-9157-9dd9f183e5a3.png)

You can see now we have different virtual folders and when trying to open a file though `cmd + p` you should get it on the first entry (which is the one from `sources://`

After this PR is merged, the same can be done for the `x` monorepo

2022-09-30 11:30 UTC, tajespasarela commented
Really really cool!! 👏🏻 👏🏻 👏🏻  well done!

Maybe it is better to move to the `@empathyco/x-archetype-utils` and export the function to keep it maintained between the different setups?

2022-10-06 19:05 UTC, diegopf commented
> Really really cool!! 👏🏻 👏🏻 👏🏻 well done!
> 
> Maybe it is better to move to the `@empathyco/x-archetype-utils` and export the function to keep it maintained between the different setups?

I like how you think! I've created https://github.com/empathyco/x/pull/760 to export the whole webpack configuration from `x-archetype-utils`.

2022-10-07 07:18 UTC, annacv commented
Hi! I'm not sure if I'm doing something wrong, but in my local environment I still see all that App.vue .
This is how it looks like:
![Captura de pantalla 2022-10-07 a les 9 09 51](https://user-images.githubusercontent.com/21217131/194494073-cf21f643-5e80-47ac-a81b-6b6de041515d.png)

I have checked PR preview link, and it's different 🤯 
![Captura de pantalla 2022-10-07 a les 9 10 41](https://user-images.githubusercontent.com/21217131/194494378-e2e89d8f-dd81-47dc-a8a8-368fb2b7eafa.png)

So it's probably something I'm missing. I have deleted `node_modules` and run `npm ci` again in case it fixed something, but it didn't work

2022-10-21 08:50 UTC, tiborux commented on package.json
> +    "install:utils:local": "npm install file:../x/packages/x-archetype-utils/empathyco-x-archetype-utils-0.1.0-alpha.2.tgz --no-save",
`"@empathyco/x-archetype-utils": "^0.1.0-alpha.4"`

2022-10-21 08:51 UTC, tiborux requested changes
gj

2022-10-21 08:51 UTC, alvarodE commented on package.json
> +    "install:utils:local": "npm install file:../x/packages/x-archetype-utils/empathyco-x-archetype-utils-0.1.0-alpha.2.tgz --no-save",
Done.

2022-10-21 08:51 UTC, alvarodE submitted a review, later dismissed

2022-10-21 11:09 UTC, mnavarroespinosa approved these changes
Good job!

2022-10-24 06:53 UTC, tiborux approved these changes

2022-10-24 06:56 UTC, merged