Translate i18n texts to Portuguese #105
empathyco/x-archetype pull request #192
Opened 2022-10-15 16:58 UTC by ClaraSantosmf

# Pull request template
 
I translated the document to Portuguese at pt.messages.json, as well as exported the messages in this file to be auto-loaded.

## Motivation and context

Now the site has a Portuguese version to display.

- [ ] Dependencies. If any, specify:
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?

Running the project locally, and accessing http://localhost:8080/?lang=pt it was possible to apply translated texts.

## Checklist:

- [X] My code follows the **[style guidelines](https://github.com/empathyco/x/blob/main/.github/CONTRIBUTING.md#style-guides)** of this project.
- [X] I have performed a **self-review** on my own code.
- [X] I have **commented** my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-10-16 22:17 UTC, ClaraSantosmf commented
Hello, can you accept my PR with the hacktoberfest tag? please

2022-10-17 08:31 UTC, herrardo commented on src/i18n/messages/pt.messages.json
> +    "base": {
I think if you do `npm install` before committing, the prettier package is installed and then the files are formatted correctly.

2022-10-17 08:38 UTC, herrardo commented on src/i18n/messages/pt.messages.json
> +    "base": {
If you want to check how your PR is working follow [these steps](https://github.com/empathyco/x-archetype#how-to-install) and then visit
http://localhost:8080/?uiLang=pt

You can change UI language by using uiLang param in the URL

2022-10-17 10:00 UTC, herrardo commented
> Hello, can you accept my PR with the hacktoberfest tag? please

Do you mean just to place #Hacktoberfest in the comment when we approve the PR?

2022-10-19 12:21 UTC, ClaraSantosmf commented on src/i18n/messages/pt.messages.json
> +    "base": {
Thanks, I fixed that already

2022-10-19 12:50 UTC, ClaraSantosmf commented on src/i18n/messages/pt.messages.json
> +        "title": "HISTÓRICO DE CONSULTAS"
Yes, the best is "histórico de buscas". I fixed this!

2022-10-19 12:56 UTC, ClaraSantosmf commented
Morning!! #Hacktoberfest

2022-10-19 14:14 UTC, herrardo requested changes
Thanks for your fixes! Just merge main into your branch to resolve the conflicts and I think you will be done!

2022-10-20 13:46 UTC, mavmaf requested changes
Hi Clara, thanks for your contribution!
Might you have merged your branch with a non-updated version of the main branch? Some files were accidentally committed. Please take a look and ensure only those files you've been working on are committed. 
Cheers!

2022-10-24 18:56 UTC, herrardo commented
@ClaraSantosmf could ypu have a look to @mavmaf comment?

For some reason you didn't update your branch properly. Thanks!

2022-11-15 15:53 UTC, closed without merging