feat: replace x-button with XDS x-button implementation
empathyco/x-archetype pull request #206
Opened 2022-11-11 09:22 UTC by CachedaCodes

EX-5908

## Motivation and context
Add `x-button` implementation from the XDS

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ X ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [ X ] `Main`
- [ ] Other. Specify:

2022-11-11 10:03 UTC, herrardo requested changes
I am comparing this PR Preview with what we have deployed in test. I see some differences.

1. There is different margin between suggestions, i guess because history queries have a button inside
![image](https://user-images.githubusercontent.com/4663897/201315874-cb4b3a98-bfbd-4dd0-bc29-c8a168ac7d99.png)

2. Have we change the font family? I see different behavior
![image](https://user-images.githubusercontent.com/4663897/201316245-f6e41dc4-8098-4a7e-8d37-31b425d8c614.png)

3. The difference between the magnifying glass button on the search input is on purpose?

![image](https://user-images.githubusercontent.com/4663897/201316653-4f7180be-1bdf-4705-bbda-8ef1c64d8117.png)

2022-11-14 15:18 UTC, CachedaCodes commented
@herrardo 

> I am comparing this PR Preview with what we have deployed in test. I see some differences.
> 
> 1. There is different margin between suggestions, i guess because history queries have a button inside

Yes, a quick fix was made in the PR, and we'll deal with it when we implement the suggestion group

> 2. Have we change the font family? I see different behavior

The one here is Montserrat, which I think is correct, the one in x.test is default sans-serif for some reason. Anyway, it should be Montserrat.

> 3. The difference between the magnifying glass button on the search input is on purpose?

Fixed, thanks!

2022-11-14 16:47 UTC, herrardo commented
> @herrardo
> 
> > I am comparing this PR Preview with what we have deployed in test. I see some differences.
> > 
> > 1. There is different margin between suggestions, i guess because history queries have a button inside
> 
> Yes, a quick fix was made in the PR, and we'll deal with it when we implement the suggestion group
> 
> > 2. Have we change the font family? I see different behavior
> 
> The one here is Montserrat, which I think is correct, the one in x.test is default sans-serif for some reason. Anyway, it should be Montserrat.
> 
> > 3. The difference between the magnifying glass button on the search input is on purpose?
> 
> Fixed, thanks!

I think the font-family is ok in test environment, we are using **Inter** font, but ask @cris-crash to be sure.

2022-11-15 07:11 UTC, CachedaCodes commented
There are known issues with the XDS button implementation that I'm currently discussing with design. I will deal with them afterwards.

Now that the `x-button` has hover effects, the size created inside of the button by its padding is noticeable in the `x-button-ghost`. In the past we used the padding of the button to align it with other elements when needed (removing it, for example), doing that now creates this effect

![image](https://user-images.githubusercontent.com/7124620/201853071-0f38d7e2-eb16-4728-b31b-6c8f65c45f0e.png)

Clear button in the searchbox is part of an input group that forces some styles (same bg color for example). The `x-button` class adds an on hover effect that changes colors, resulting in this effect when hovering the clear button.

![image](https://user-images.githubusercontent.com/7124620/201853093-f97e4f00-1d4a-4263-bfce-061596d85a72.png)

Sometimes, the new hover effects and its interaction with the `x-button-ghost` produce weird results depending on the background the button is or the elements inside the icon.

![image](https://user-images.githubusercontent.com/7124620/201853127-2a8610b8-cf6c-4573-a75b-8af126aeec47.png)

![image](https://user-images.githubusercontent.com/7124620/201853141-247e6354-5a32-455f-b993-d640d47a2fe4.png)

The button size changing makes it so elements previously aligned now are not.

![image](https://user-images.githubusercontent.com/7124620/201853173-844fec16-209c-4986-8f75-808f9466d8c7.png)

Some combinations of bg color and font are not possible with the DS or clash with it

![image](https://user-images.githubusercontent.com/7124620/201853206-3f8abc92-d9c1-4962-ad5e-08257c0a1fd4.png)

![image](https://user-images.githubusercontent.com/7124620/201853233-3379c170-86f6-4a54-adc6-790f51c44021.png)

2022-11-15 14:33 UTC, tiborux commented on src/components/search/results/mobile-partial-results.vue
> +          class="x-button-lead x-button-ghost x-margin--left-auto"
Removing the x-text the font-size changes, I supposed that this is right

2022-11-15 14:42 UTC, tiborux requested changes
gj

2022-11-15 14:44 UTC, tiborux commented
You missed the next-query:

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/6597815/201947946-1e1d92b2-9613-4f07-b936-f01d678045b8.png">

2022-11-16 08:36 UTC, mnavarroespinosa requested changes
Good job!

2022-11-16 10:01 UTC, CachedaCodes commented
> You missed the next-query:
> 
> <img alt="image" width="1465" src="https://user-images.githubusercontent.com/6597815/201947946-1e1d92b2-9613-4f07-b936-f01d678045b8.png">

This one is technically a suggestion, which will be its own component, so it shouldn't be changed.

2022-11-16 14:01 UTC, tiborux approved these changes
gj

2022-11-16 14:33 UTC, mnavarroespinosa approved these changes

2022-11-16 14:37 UTC, tiborux approved these changes

2022-11-16 14:43 UTC, merged