feat(archetype): apply Design System to the archetype
empathyco/x-archetype pull request #21
Opened 2021-06-16 11:30 UTC by tajespasarela

EX-3868

2021-06-16 11:31 UTC, tajespasarela commented
The purpose of this PR is to use the Design System in the Archetype to apply styles.

2021-06-16 12:44 UTC, pmareke requested changes
Great job!

2021-06-16 12:44 UTC, pmareke commented on src/design-system/tokens.scss
> +  --x-color-lead: #36515b;
The default colors are:

```
  --x-color-lead: #36515b;
  --x-color-auxiliary: #667981;
  --x-color-neutral-10: #1a1a1a;
  --x-color-neutral-35: #595959;
  --x-color-neutral-70: #b3b3b3;
  --x-color-neutral-95: #f2f2f2;
  --x-color-neutral-100: #ffffff;
```

So I think you can delete 

- --x-color-lead
-  --x-color-neutral-10
-  --x-color-neutral-35
-  --x-color-neutral-100

2021-06-17 06:50 UTC, pmareke approved these changes
LGTM

2021-06-17 07:23 UTC, davidmfempathy approved these changes

2021-06-17 07:24 UTC, merged