feat(design-system): use suggestion and suggestion group from x-tailwindcss
empathyco/x-archetype pull request #238
Opened 2023-01-11 13:32 UTC by tiborux

EX-7492

2023-01-11 17:47 UTC, herrardo reviewed
@cris-crash I would like to review this one with you to understand some things better.

2023-01-12 11:59 UTC, ajperezbau requested changes
Good job 👌

2023-01-13 08:42 UTC, tiborux commented on src/components/my-history/custom-my-history.vue
>          </div>
<img width="287" alt="image" src="https://user-images.githubusercontent.com/6597815/212276325-1aebc3ca-1b20-42a3-8dd9-bf0f7bbf9153.png">

2023-01-13 09:10 UTC, ajperezbau commented on src/components/my-history/custom-my-history.vue
>          </div>
I think that what she is saying is that the picture on the left is the better 🤣

2023-01-13 09:29 UTC, herrardo requested changes
Some things that we are seeing because of this PR:

1. Change My History and Clear All buttons from ghost to tight, to align with suggestions
![image](https://user-images.githubusercontent.com/4663897/212283488-f0da864f-b018-4ea3-baf9-7fc8e39aa8ed.png)

2.Align Top Clicked with History Queries title 
![image](https://user-images.githubusercontent.com/4663897/212283584-19e43c43-40df-4ba9-84b3-551f23036ecb.png)

3. Align delete icon in suggestions to the right in desktop, mobile, and my history as Alicia proposed
![image](https://user-images.githubusercontent.com/4663897/212284174-b2827f80-f265-486f-824d-76890f1093fc.png)
![image](https://user-images.githubusercontent.com/4663897/212284251-34113091-820a-4a07-9d73-821550f445f5.png)

4. Change suggestions to lg size **only in mobile**
5. Change My History Suggestion padding from padding-04 to padding-02, top&bottom

6. With the new suggestions, we have lost the alignment of elements in mobile between the input text and the suggestions:

Before
![image](https://user-images.githubusercontent.com/4663897/212286947-a9b7dcb6-266f-46e4-9c2e-94459dd2331c.png)

After
![image](https://user-images.githubusercontent.com/4663897/212286905-3361cd0f-180a-4462-be9a-8f971f45c2eb.png)
 
Review performed by @herrardo and @cris-crash  :)

2023-01-13 11:12 UTC, tiborux commented on src/components/my-history/custom-my-history.vue
>          </div>
im retarded sorry

2023-01-20 08:34 UTC, herrardo requested changes
- The gap between the icon and the suggestion in Popular Searches is to wide, it should be as in history queries 
![Uploading image.png…]()

@cris-crash is coming to you with this @tiborux

2023-01-20 10:48 UTC, ajperezbau requested changes
Good job 👌

2023-01-20 10:48 UTC, ajperezbau commented on src/components/my-history/custom-my-history.vue
>          </div>
Should the close buttons be aligned with the switch?

<img width="495" alt="image" src="https://user-images.githubusercontent.com/75546736/213674057-40467265-706f-462e-88c7-8de4de30a89c.png">

2023-01-20 10:48 UTC, ajperezbau commented on src/components/predictive-layer/predictive-layer.vue
>          v-slot="{ identifierResult }"
It seems that the query suggestions are not being highlighted.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/75546736/213674711-6b6b621f-326f-4490-84dd-f29f8b163564.png">

2023-01-23 08:21 UTC, ajperezbau approved these changes
Good job 👌

2023-01-23 12:18 UTC, cris-crash approved these changes

2023-01-23 12:19 UTC, ajperezbau approved these changes

2023-01-23 12:56 UTC, herrardo approved these changes

2023-01-23 13:16 UTC, merged