Feature/ex 4187 the sort dropdown is overlapped
empathyco/x-archetype pull request #24
Opened 2021-07-05 09:04 UTC by davidmfempathy

# Description

Two different commits (don't squash, just merge to keep them separated).
- main.vue: removed CSS done in the past to fix something related to the staggered fade and slide animation.
- toolbar.vue: add CollapseFromTop transition.

Initially, the task describes an issue that I haven't been able to reproduce. Please, check if it happens to you but it seems that it has been fixed.

Testing it (you have to animate the sort dropdown), I noticed that something was wrong because there was a delay, pause between the start and the end of the sort animation if I use CollapseHeight. It seems to be a performance issue that doesn't happen with CollapseFromTop animation which uses scale instead of modifying the height.

# Motivation

Related issue from the original described in the task that I couldn't reproduce.

# Test

Run the server and check if the sort dropdown is overlapping any result element; check also the animation.

2021-07-05 10:34 UTC, CachedaCodes commented
Couldn't reproduce the issue described in the task but found one that might be related.
While the dropdown is open, hovering over a result under the dropdown will result in the "Add to cart" button popping over the dropdown.

![image](https://user-images.githubusercontent.com/7124620/124458320-1bb66e80-dd8d-11eb-98d6-20da2d00d57c.png)

I would say it's similar enough to the described issue that it makes sense to handle it in this PR.

- [ ] Fix "Add to Cart button popping over dropdown"

2021-07-05 10:45 UTC, CachedaCodes requested changes
Couldn't reproduce the issue described in the task but found one that might be related.
While the dropdown is open, hovering over a result under the dropdown will result in the "Add to cart" button popping over the dropdown.

![image](https://user-images.githubusercontent.com/7124620/124458320-1bb66e80-dd8d-11eb-98d6-20da2d00d57c.png)

I would say it's similar enough to the described issue that it makes sense to handle it in this PR.

- [x] Fix "Add to Cart button popping over dropdown"

2021-07-12 09:05 UTC, CachedaCodes approved these changes

2021-07-12 12:38 UTC, tiborux approved these changes

2021-07-12 12:45 UTC, merged