feat(styles) Archetype recurring changes
empathyco/x-archetype pull request #241
Opened 2023-01-18 08:48 UTC by annacv

[EX-7224](https://searchbroker.atlassian.net/browse/EX-7274)

There is some stuff in the list that was already fixed. Here is the list of things applied: 

- Change grid mobile token
- Column picker inside toolbar: differentiate selected from not selected.
- Add the identifier result’s title translation key everywhere missing
- Mobile aside & desktop aside spacings
- Sort&Filter lists spacings

Take in account: not doing anything inside predictive as there's a PR opened that will fix some stuff

2023-01-20 10:17 UTC, LuisMartinez15 submitted a review, later dismissed
**praise:** good job! 👏🏿

2023-01-20 12:16 UTC, ajperezbau requested changes
Good job 👌

2023-01-20 12:16 UTC, ajperezbau commented on src/design-system/tokens.scss
> +  --x-size-padding-top-filter-default: var(--x-size-base-0);
This token does not exist.

2023-01-20 14:01 UTC, annacv commented on src/design-system/tokens.scss
> +  --x-size-padding-top-filter-default: var(--x-size-base-0);
#shame XD Thks @ajperezbau

2023-01-23 08:29 UTC, ajperezbau approved these changes
Good job 👌

2023-01-23 08:54 UTC, LuisMartinez15 approved these changes
good job!

2023-01-23 08:56 UTC, merged