Feature/ex 4242 update archetype documentation a
empathyco/x-archetype pull request #25
Opened 2021-07-07 11:14 UTC by davidmfempathy

# What

- Update Archetype documentation according to the new Github scenario. I've include information about the DS, how to clone and run it, etc.
- Update i18n documentation according to the new x-translations package added recently.

# Motivation

The documentation was outdated.

# Test

- Check that the milestones from the task are fulfilled.
- Suggest any new change.

2021-07-08 07:27 UTC, tiborux submitted a review, later dismissed

2021-07-08 09:30 UTC, CachedaCodes requested changes

2021-07-08 09:30 UTC, CachedaCodes commented on docs/index.md
> +We recommend to use [Degit](https://github.com/Rich-Harris/degit) which let us copying a project without the `.git`
Same as above about the file extension format

2021-07-08 09:30 UTC, CachedaCodes commented on docs/index.md
> +We recommend to use [Degit](https://github.com/Rich-Harris/degit) which let us copying a project without the `.git`
Change to "We recommend using [Degit]".

- [ ] Fix typo

2021-07-08 09:30 UTC, CachedaCodes commented on docs/index.md
> +You can take a look to the [X Components design system README](https://github.com/empathyco/x/tree/main/packages/x-components/contributing/design-system.md)
Change to "You can take a look at the".

- [ ] Fix typo

2021-07-08 11:48 UTC, davidmfempathy commented on docs/i18n.md
> +We created a library for managing the i18n translations easier. It transforms the application i18n files in .csv files
I've changed both to .csv which makes clearer that it's an extension in my opinion.

2021-07-09 06:14 UTC, CachedaCodes approved these changes

2021-07-09 06:25 UTC, tiborux approved these changes

2021-07-09 06:27 UTC, merged