feat: unify results preview carousels styles
empathyco/x-archetype pull request #263
Opened 2023-02-16 15:51 UTC by ajperezbau

EX-7325

2023-02-20 07:58 UTC, annacv commented on src/components/pre-search/custom-query-preview.vue
> +          <ItemsList :items="results" class="x-flex x-gap-16 x-pt-16 max-desktop:x-px-16">
```suggestion
          <ItemsList :items="results" class="x-flex x-gap-16 x-pt-4 max-desktop:x-pt-0 max-desktop:x-px-16">
```
Distance between `BaseEventButton` it's less in designs, 16px & 10px mobile. As the button has its own white space inside, I think the padding defined should be a bit less.

2023-02-20 08:13 UTC, annacv requested changes
Hi! I've seen some little things : 
- Less distance between `BaseEventButton` and `ItemsList`:  as the button has its own internal white space the padding defined should be less.
- Product Name is in uppercase
- Mobile: There is no Product Description
- Mobile: In `NextQueryPreview`, the distance between the text and the button should be the same when there are 2 lines of text + button, check it for 375px screens as below:
![Captura de pantalla 2023-02-20 a les 9 12 04](https://user-images.githubusercontent.com/21217131/220049147-07e1a1f1-bc55-4cee-9fef-e5ccb7e94c74.png)

2023-02-22 10:02 UTC, mnavarroespinosa requested changes
good job!

2023-02-27 10:45 UTC, tiborux commented on src/components/my-history/custom-my-history.vue
> +                    <HistoryIcon :class="{ 'x-icon-lg': $x.device === 'mobile' }" />
```suggestion
                    <HistoryIcon class="max-desktop:x-icon-lg" />
```

2023-02-27 15:01 UTC, herrardo commented
This seems great!

2023-02-27 16:04 UTC, annacv approved these changes

2023-02-28 09:33 UTC, mnavarroespinosa approved these changes
Looks good to me, good job!

2023-02-28 09:33 UTC, merged