feature: ingest any url parameter in the snippet
empathyco/x-archetype pull request #269
Opened 2023-03-22 15:27 UTC by CachedaCodes

EX-7917

## Motivation and context
We needed to be able to get any parameter from the URL even if we don't specify it in the snippet (for testing reasons explained in the task description).

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?
Load a query with random parameters and check that they're present in `window.initX` along with the other parameters that we're already handling from the snippet.

2023-03-27 11:01 UTC, diegopf requested changes
I think it is okay for the goal of this PR but just highlight that clear the query will not remove from the url any additional query parameters.

2023-03-28 06:53 UTC, mnavarroespinosa commented on public/snippet-script.js
> +  return undefined;
I agree with @diegopf. Besides we can extract the parameter value at first too if you like it.

```
function popURLParameter(parametersDictionary, parameterKey) {
  const parameterValue = parametersDictionary[parameterKey];
  if(parameterValue) {
    delete parametersDictionary[parameterKey];
    return parameterValue;
  }
}
```

2023-03-28 10:59 UTC, CachedaCodes commented on public/snippet-script.js
I kind of remember that using `const` would mess up the build in the past, but I'll try.

2023-03-30 10:24 UTC, herrardo approved these changes

2023-03-30 10:47 UTC, diegopf approved these changes

2023-03-30 10:48 UTC, merged