Add Selected Filters in myHistory
empathyco/x-archetype pull request #332
Opened 2023-10-16 08:41 UTC by annacv

[EMP-2293](https://searchbroker.atlassian.net/browse/EMP-2293)

Implement `selectedFilters` in myHistory aside panel.
Test: 
Choose & query and filter with one or more filters, check the aside panel & see filters shown below the query

2023-10-16 13:39 UTC, CachedaCodes requested changes

2023-10-16 13:39 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +              <ul v-if="suggestion.selectedFilters" class="x-flex x-gap-8">
Doesn't look good when there are long/a lot of filters

![image](https://github.com/empathyco/x-archetype/assets/7124620/afc8439e-e9d3-40e8-8394-039c0907de2b)

2023-10-16 13:39 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +                  class="x-text1-sm x-text-auxiliary-50"
`auxiliary-50` on white background doesn't pass the WCAG contrast test. Maybe better to have it the same as the timestamp.

2023-10-16 13:39 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +              <ul v-if="suggestion.selectedFilters" class="x-flex x-gap-8">
The `v-if="suggestion.selectedFilters"` condition is passing even when there are no filters. An empty array returns `true` when converted to boolean. Use `length`.

2023-10-26 09:22 UTC, support-empathy commented
Check **PR 332** preview 👀 <br> <br> [https://x.test.empathy.co/preview/332/index.html](https://x.test.empathy.co/preview/332/index.html)

2023-10-26 14:48 UTC, support-empathy commented
Check **PR 332** preview 👀 <br> <br> [https://x.test.empathy.co/preview/332/index.html](https://x.test.empathy.co/preview/332/index.html)

2023-10-30 10:57 UTC, CachedaCodes requested changes

2023-10-30 10:57 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +            suggestionClass="x-suggestion x-w-[320px]"
We already have `320px` as value in the theme's spacing

2023-10-30 10:57 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +                <p class="x-line-clamp-1">
Using a line clamp of 1 is overkill, this should be done just with `x-truncate`.

The width limit should be here, not in the parent.

2023-10-30 10:57 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +                <p class="x-pl-8">({{ suggestion.selectedFilters.length }})</p>
You're adding extra `8px` between the last filter and the filter count with this padding.
Also this should be an span

```suggestion
                <span>({{ suggestion.selectedFilters.length }})</span>
```

2023-10-30 10:57 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +                v-if="suggestion.selectedFilters && suggestion.selectedFilters.length > 0"
```suggestion
                v-if="suggestion.selectedFilters && suggestion.selectedFilters.length"
```

2023-10-30 10:57 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +              <p class="hover:x-underline">{{ suggestion.query }}</p>
This way you only get the underline when hovering this specific element. This underline should appear when you hover anywhere in the parent.
Use [tailwind group](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state) for this

2023-10-30 10:57 UTC, CachedaCodes commented on src/tailwind/plugin-options.js
> +    '.history-query.suggestion-group:hover': {
This removes the hover decorations to all HQ, including the ones in the empathize.
You can deactivate the text decoration in the history query with tailwind.

2023-10-30 10:58 UTC, CachedaCodes commented
The filters under the HQs in the empathize are missing

2023-10-30 14:59 UTC, herrardo requested changes

2023-10-30 14:59 UTC, herrardo commented on src/components/my-history/custom-my-history.vue
> +                  {{ filter.label ?? filter.id }}
```suggestion
                  {{ filter.label }}
```

You can accept this commit by pointing to x-components "3.0.1-alpha.1"

2023-10-31 11:12 UTC, support-empathy commented
Check **PR 332** preview 👀 <br> <br> [https://x.test.empathy.co/preview/332/index.html](https://x.test.empathy.co/preview/332/index.html)

2023-10-31 14:04 UTC, CachedaCodes requested changes

2023-10-31 14:04 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +                <div class="x-line-clamp-1">
You're still using line clamp instead of truncate.
Also, this should have a width of 320px aprox.

2023-10-31 14:04 UTC, CachedaCodes commented on src/components/predictive-layer/full-width-predictive.vue
> +                                    <div class="x-line-clamp-1">
Change this line clamp with truncate

2023-10-31 14:04 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +              <div
This is a pretty big chunk that is duplicated here and in the empathize, moving it to it's own component might be a good idea.

2023-10-31 14:04 UTC, CachedaCodes commented on src/tailwind/plugin-options.js
> +    '.history-query.suggestion-group:hover': {
This is still here and it's not needed

2023-11-02 08:16 UTC, support-empathy commented
Check **PR 332** preview 👀 <br> <br> [https://x.test.empathy.co/preview/332/index.html](https://x.test.empathy.co/preview/332/index.html)

2023-11-02 13:40 UTC, CachedaCodes requested changes
gj!

The HQ in mobile don't have the filters, I think it's because mobile uses the `PredictiveLayer` component instead of the full width one

2023-11-02 13:40 UTC, CachedaCodes commented on src/components/history-query-filters.vue
> +<style scoped></style>
```suggestion
```

2023-11-02 13:40 UTC, CachedaCodes commented on src/components/my-history/custom-my-history.vue
> +              <HistoryQueryFilters class="x-w-192" :suggestion="suggestion"></HistoryQueryFilters>
```suggestion
              <HistoryQueryFilters class="x-w-192" :suggestion="suggestion"/>
```

Also, the list of filters could be have more width here, bump it to something around 250-320

2023-11-02 14:59 UTC, support-empathy commented
Check **PR 332** preview 👀 <br> <br> [https://x.test.empathy.co/preview/332/index.html](https://x.test.empathy.co/preview/332/index.html)

2023-11-02 15:15 UTC, support-empathy commented
Check **PR 332** preview 👀 <br> <br> [https://x.test.empathy.co/preview/332/index.html](https://x.test.empathy.co/preview/332/index.html)

2023-11-02 15:19 UTC, support-empathy commented
Check **PR 332** preview 👀 <br> <br> [https://x.test.empathy.co/preview/332/index.html](https://x.test.empathy.co/preview/332/index.html)

2023-11-03 07:18 UTC, CachedaCodes approved these changes

2023-11-03 07:20 UTC, merged